version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - "5432:5432"


  web:
    depends_on:
      - db
    build: .
    env_file:
      - .env
    #command: sh -c "sleep 8 && chmod +x /app/migrate.sh && sh /app/migrate.sh && chmod +x /app/createsuperuser.sh && sh /app/createsuperuser.sh && /app/entrypoint.sh"
    command: sh -c "sleep 8 && chmod +x /app/createnv.sh && sh /app/createnv.sh && chmod +x /app/migrate.sh && sh /app/migrate.sh && chmod +x /app/createsuperuser.sh && sh /app/createsuperuser.sh && /app/entrypoint.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"




