apiVersion: apps/v1
kind: Deployment
metadata:
  name: molla-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: molla-deployment
  template:
    metadata:
      labels:
        app: molla-deployment
    spec:
      containers:
        - name: molla
          image: yoness/molla
          envFrom:
            - configMapRef:
                name: gateway-configmap
          ports:
            - containerPort: 8000