apiVersion: v1
kind: Service
metadata:
  name: molla-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: molla-deployment

