# Generated by Django 3.2.19 on 2023-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_rate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../static/default_category.png', upload_to='categories_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
