# Generated by Django 3.2.19 on 2023-11-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='settings.STATIC_ROOT/default_product.png', upload_to='products_images/'),
        ),
    ]
