# Generated by Django 3.2.23 on 2023-11-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../static/default_category.png', upload_to='categories_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_back',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cross',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_side',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_with_model',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
    ]
