# Generated by Django 3.2.23 on 2023-11-22 18:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0009_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('mount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='../static/default_category.png', upload_to='categories_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_back',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cross',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_side',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_with_model',
            field=models.ImageField(default='../static/default_product.png', upload_to='products_images/'),
        ),
    ]
