# Generated by Django 3.2.23 on 2023-11-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('base', '0010_auto_20231122_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
